# Exported from Render on 2025-07-16T07:29:15Z
services:
- type: web
  name: vibe-trading-app-api-gateway
  runtime: docker
  repo: https://github.com/faculax/vibe-iac2
  branch: main
  plan: free
  region: frankfurt
  dockerContext: .
  dockerfilePath: services/api-gateway/Dockerfile
  autoDeployTrigger: "off"
- type: web
  name: vibe-trading-app-trader-ui
  runtime: docker
  repo: https://github.com/faculax/vibe-iac2
  branch: main
  plan: free
  region: frankfurt
  dockerContext: .
  dockerfilePath: Dockerfile
  autoDeployTrigger: "off"
  rootDir: ui/trader-ui/
- type: web
  name: vibe-trading-app-oms
  runtime: docker
  repo: https://github.com/faculax/vibe-iac2
  branch: main
  plan: free
  region: frankfurt
  dockerContext: .
  dockerfilePath: services/order-management-system/Dockerfile
  autoDeployTrigger: "off"
- type: web
  name: vibe-trading-app-client-ui
  runtime: docker
  repo: https://github.com/faculax/vibe-iac2
  branch: main
  plan: free
  region: frankfurt
  dockerContext: .
  dockerfilePath: Dockerfile
  autoDeployTrigger: "off"
  rootDir: ui/client-ui/
version: "1"

